### ISSUE TITLE
An item with the same key has already been added. Key: @odata.type

### ISSUE THREAD

**Issue by dalvirsaini** [microsoftgraph/dotnetcore-console-sample#59]
I am facing this issue while creating multiple tasks under same plan. 

https://stackoverflow.com/questions/60035078/ms-graph-sdk-planner-tasks-an-item-with-the-same-key-has-already-been-added

**Comment by BrianTJackett** [comment]
@dalvirsaini Thank you for raising this.  Investigating and will update you on findings.

**Comment by BrianTJackett** [comment]
@dalvirsaini It looks like the problem is occurring with the "Assignments = assignments," line as the variable "assignments" can't re-add the same user ID to the dictionary multiple times.  I would recommend not adding multiple tasks within a single function execution of CreatePlannerTask().  Instead call that function multiple times and pass in the various parameters needed to create multiple tasks.

**Comment by dalvirsaini** [comment]
ok got it
